version: '3'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data_postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: js-container
    ports:
      - '9999:9999'


